Switched to using git to clone qwt to bypass 403 forbidden

diff --git a/.github/workflows/build-caqtdm.yml b/.github/workflows/build-caqtdm.yml
--- a/.github/workflows/build-caqtdm.yml
+++ b/.github/workflows/build-caqtdm.yml
@@ -33,6 +33,7 @@ jobs:
           zeromq \
           python \
           qt6-5compat \
+          qt6-websockets \
           git \
           ncurses \
           perl \
@@ -133,7 +134,17 @@ jobs:
 
           cd \"\$AUR_DIR\" || { echo \"Error: Initial change to \$AUR_DIR failed.\"; exit 1; }
           
-          install_aur_package qwt-qt6
+          if git_clone_aur_with_fallback qwt-qt6; then
+            cd qwt-qt6 || { echo \"Error: Could not change to qwt-qt6 directory.\"; exit 1; }
+            sed -i 's|^source=.*|source=("git+https://git.code.sf.net/p/qwt/git#tag=v${pkgver}")|' PKGBUILD
+            sed -i "s|^sha256sums=.*|sha256sums=('SKIP')|" PKGBUILD
+            sed -i 's|cd qwt-${pkgver}|cd git|' PKGBUILD
+            makepkg -si --noconfirm
+            cd \"\$AUR_DIR\" || { echo \"Error: Could not change back to \$AUR_DIR.\"; exit 1; }
+          else
+            echo \"Skipping 'qwt-qt6' due to cloning failure.\"
+          fi
+
           install_aur_package epics-base
         "
       shell: bash
